application: algae
version: 1
runtime: python27
threadsafe: false
api_version: 1

default_expiration: "14d"

builtins:
- remote_api: on
- appstats: on

handlers:
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  
- url: /favicon.ico
  static_files: static/img/favicon.ico
  upload: static/img/favicon.ico
  
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
  
- url: /robots.txt
  static_files: static/humans.txt
  upload: static/humans.txt
  
- url: /static/css
  static_dir: static/css
  
- url: /static/img
  static_dir: static/img
 
- url: /static/js
  static_dir: static/js 
  
- url: /.*
  script: app.py
  
libraries:
- name: jinja2
  version: "2.6"
  
- name: webapp2
  version: "2.3"